# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$directory$git_branch
$character"""

# Inserts a blank line between shell prompts
add_newline = false

[package]
disabled = false

[username]
show_always = true
style_user = "green bold"
style_root = "red bold"
format = "[$user: ]($style)"
disabled = false

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
# vi stuff
vicmd_symbol = "[❮](bold yellow)"
vimcmd_visual_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"


[directory]
read_only = "[R]"
read_only_style = "bold red"
truncation_length = 0
format = "[$path]($style)> "

[shell]
bash_indicator = "bsh"
zsh_indicator = "zsh"
fish_indicator = ''
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
disabled = false
